package edu.neu.khoury.cs5004.assignment7.problem2;

public enum MovingViolation {
  DISTRACTEDDRIVING,RECKLESSDRIVING,SPEEDING,DRIVINGNUMBERINFLUENCE,
  FAILURETORESPECTTRAFFICSIGNS,DRIVINGWITHOUTAVALIDLICENSEANDORINSURANCE;
}
